### ISSUE TITLE
Support hooks before/after command and message handling

### ISSUE THREAD

**Issue by Sodre177** [Intery/dpy-cmdClient#7]
Allow setting up hooks which are executed before or after commands are executed or messages are read. Allow these to be customised in a simple way per-command to allow creation of command groups with different overall behaviour.

This could be through subclassing `cmdClient` itself and setting attributes reminiscent of the `contextBot` command handler system, or through adding decorators for the same.

Keep in mind the possibility of using decorators from the `Command` objects resulting from command definition.
A simpler method might be to create a decorator which creates a command decorator from a function which takes in the command and execution context.

**Comment by Intery** [comment]
# Implementation Proposal
Create a `Module` module in the vein of `commandHandler` with an extension interface as well as a decorator interface for command execution wrappers.

Store a `baseModule` subclass of `Module` as an attribute of the client, optionally supplied on initialisation. Similarly accept a `baseCommand` class for generating commands.
On initialisation, create an instance of the `base_module` to be used for commands which do not specify a module.
 
Add a classmethod decorator to `client` to create a module, optionally accepting a `Module` subclass, otherwise using `base_module`.

Global default before/after hooks for commands may be created in `baseModule` and passed to the client.
Module specific before/after hooks may be created via Module instance decoration methods.

Allow two methods of command creation. 
* Directly from a raw command decorator (the current situation), optionally accepting a module but otherwise using the default module.
* From a `Module` decorator method.

The associated module is added as an attribute to the command, and the execution logic occurs in the client. The module does not apply its own decorators to the command (as in `contextBot`), and instead provides its methods for use by the client in execution.

Modules should provide a decorator method for adding initialisation steps (thereby also implementing `load_into` in #5).
Potential extra features include clearing cache and reloading for individual modules, an in-built "ready" mechanism, and live enabling/disabling of modules.

Modules may then be loaded via a standard import, which provides a solution to the double-loading issue in #4, and, via standard python module logic, to the recursive loading requested in #3.

Hooks for raw pre-message handling are best added directly as decorators in the client, or even directly through the pre-existing `on_message` decorator, matching the discord.py command extension philosophy.
